- name: Install networking dependencies and containerd
  apt:
    name:
      - kubernetes-cni
      - containernetworking-plugins
      - socat
      - containerd
      - conntrack
    state: present
    update_cache: yes

- name: Create containerd config directory and default config
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
    systemctl restart containerd

- name: Create CNI directory and link plugins
  shell: |
    mkdir -p /opt/cni/bin
    cp /usr/lib/cni/* /opt/cni/bin/ || true
    ln -sf /usr/lib/cni/* /opt/cni/bin/ || true

- name: Hard reset minikube
  shell: rm -rf /root/.minikube /root/.kube /etc/kubernetes /var/lib/minikube
  ignore_errors: yes

- name: Start Minikube
  command: minikube start --driver=none --force --container-runtime=containerd