- name: Install networking dependencies and containerd
  apt:
    name:
      - kubernetes-cni
      - socat
      - containerd
      - conntrack
      - cri-tools
    state: present
    update_cache: yes

- name: Force delete old minikube configs
  shell: rm -rf /root/.minikube /root/.kube /etc/kubernetes /var/lib/minikube
  ignore_errors: yes

- name: Start Minikube
  command: minikube start --driver=none --force --container-runtime=containerd --memory=2048mb --extra-config=kubeadm.ignore-preflight-errors=NumCPU,Mem --v=5